// SPDX-License-Identifier: AGPL-3.0-or-later
// The GraphQL Code Generator config of the web, which pnpm gen runs (scripts/gen.mjs). Each
// <operation>.graphql.ts in src holds one named operation; the generator writes the operation's
// result and variable types and its typed document to <operation>.graphql.gen.ts next to it, from
// the backend's schema in schema/api.graphql.

import { globSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { type CodegenConfig, generate } from '@graphql-codegen/cli';

const webDir = import.meta.dirname;

/** The first line of every generated file. */
const header =
  '// Generated by pnpm gen from schema/api.graphql and the .graphql.ts file next to it. Do not edit.\n';

/**
 * The plugin config that Apollo Client's GraphQL Codegen guide recommends, with readonly types,
 * type-only imports and Apollo's own TypedDocumentNode, which the hooks infer their types from.
 */
const pluginConfig = {
  // null for a nullable field instead of an optional one; a nullable input field may be left out.
  avoidOptionals: { field: true, inputValue: false },
  // A scalar without a mapping is unknown, never any.
  defaultScalarType: 'unknown',
  // The cache adds __typename to every object below the root.
  nonOptionalTypename: true,
  skipTypeNameForRoot: true,
  immutableTypes: true,
  useTypeImports: true,
  documentNodeImport: '@apollo/client#TypedDocumentNode',
};

/** The web's operation files, as sorted paths relative to apps/web. */
export function documentFiles(): string[] {
  return globSync('src/**/*.graphql.ts', { cwd: webDir }).sort();
}

/**
 * The config for a schema file: one output per operation file, next to it. Without a preset each
 * output reads only its own operation file, so it holds the input and enum types its operation
 * uses, and a fragment is not shared across operation files.
 */
export function codegenConfig(schema: string): CodegenConfig {
  const generates: CodegenConfig['generates'] = {};
  for (const file of documentFiles()) {
    generates[file.replace(/\.ts$/, '.gen.ts')] = {
      documents: file,
      plugins: ['typescript-operations', 'typed-document-node'],
      config: pluginConfig,
    };
  }
  return { schema, generates, silent: true, errorsOnly: true };
}

/** A generated file: its path relative to apps/web and its text. */
export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
}

/**
 * Generates the typed documents of every operation file from the schema file, without writing
 * them. A document that the schema does not validate rejects, naming the field.
 */
export async function generateDocuments(schema: string): Promise<GeneratedFile[]> {
  const outputs: { filename: string; content: string }[] = await generate(
    { ...codegenConfig(schema), cwd: webDir },
    false,
  );
  return outputs
    .map(({ filename, content }) => ({
      path: relative(webDir, resolve(webDir, filename)),
      content: `${header}${content.endsWith('\n') ? content : `${content}\n`}`,
    }))
    .sort((a, b) => a.path.localeCompare(b.path));
}
