// Generated by pnpm gen from schema/api.graphql and the .graphql.ts file next to it. Do not edit.
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { TypedDocumentNode as DocumentNode } from '@apollo/client';
export type CorePermissionCatalogQueryVariables = Exact<{ [key: string]: never; }>;


export type CorePermissionCatalogQuery = { readonly corePermissionCatalog: ReadonlyArray<{ readonly __typename: 'PermissionModule', readonly moduleId: string, readonly resources: ReadonlyArray<{ readonly __typename: 'PermissionResource', readonly resource: string, readonly permissions: ReadonlyArray<{ readonly __typename: 'Permission', readonly key: string, readonly installed: boolean }> }> }> };


export const CorePermissionCatalogDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CorePermissionCatalog"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"corePermissionCatalog"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"moduleId"}},{"kind":"Field","name":{"kind":"Name","value":"resources"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"resource"}},{"kind":"Field","name":{"kind":"Name","value":"permissions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"key"}},{"kind":"Field","name":{"kind":"Name","value":"installed"}}]}}]}}]}}]}}]} as unknown as DocumentNode<CorePermissionCatalogQuery, CorePermissionCatalogQueryVariables>;
