// Generated by pnpm gen from schema/api.graphql and the .graphql.ts file next to it. Do not edit.
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { TypedDocumentNode as DocumentNode } from '@apollo/client';
export type CoreCompaniesQueryVariables = Exact<{ [key: string]: never; }>;


export type CoreCompaniesQuery = { readonly coreCompanies: ReadonlyArray<{ readonly __typename: 'Company', readonly id: string, readonly name: string, readonly plants: ReadonlyArray<{ readonly __typename: 'Plant', readonly id: string, readonly slug: string, readonly name: string }> }> };


export const CoreCompaniesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CoreCompanies"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"coreCompanies"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"plants"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"slug"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]}}]} as unknown as DocumentNode<CoreCompaniesQuery, CoreCompaniesQueryVariables>;
