// Generated by pnpm gen from schema/api.graphql and the .graphql.ts file next to it. Do not edit.
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { TypedDocumentNode as DocumentNode } from '@apollo/client';
export type RoleOrigin =
  | 'CUSTOM'
  | 'MODULE';

export type ScopeKind =
  | 'COMPANY'
  | 'PLANT';

export type CoreRolesQueryVariables = Exact<{ [key: string]: never; }>;


export type CoreRolesQuery = { readonly coreRoles: ReadonlyArray<{ readonly __typename: 'Role', readonly id: string, readonly name: string, readonly origin: RoleOrigin, readonly moduleId: string | null, readonly permissions: ReadonlyArray<string>, readonly version: number, readonly holders: ReadonlyArray<{ readonly __typename: 'RoleAssignment', readonly id: string, readonly scope: { readonly __typename: 'AccessScope', readonly id: string, readonly kind: ScopeKind } }> }> };


export const CoreRolesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CoreRoles"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"coreRoles"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"origin"}},{"kind":"Field","name":{"kind":"Name","value":"moduleId"}},{"kind":"Field","name":{"kind":"Name","value":"permissions"}},{"kind":"Field","name":{"kind":"Name","value":"version"}},{"kind":"Field","name":{"kind":"Name","value":"holders"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"scope"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"kind"}}]}}]}}]}}]}}]} as unknown as DocumentNode<CoreRolesQuery, CoreRolesQueryVariables>;
