// Generated by pnpm gen from schema/api.graphql and the .graphql.ts file next to it. Do not edit.
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { TypedDocumentNode as DocumentNode } from '@apollo/client';
export type CoreViewerQueryVariables = Exact<{ [key: string]: never; }>;


export type CoreViewerQuery = { readonly coreViewer: { readonly __typename: 'Viewer', readonly userId: string, readonly plantPermissions: ReadonlyArray<string>, readonly companyPermissions: ReadonlyArray<string> } };


export const CoreViewerDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CoreViewer"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"coreViewer"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"userId"}},{"kind":"Field","name":{"kind":"Name","value":"plantPermissions"}},{"kind":"Field","name":{"kind":"Name","value":"companyPermissions"}}]}}]}}]} as unknown as DocumentNode<CoreViewerQuery, CoreViewerQueryVariables>;
