// Generated by pnpm gen from schema/api.graphql and the .graphql.ts file next to it. Do not edit.
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { TypedDocumentNode as DocumentNode } from '@apollo/client';
export type PlanningBoardQueryVariables = Exact<{ [key: string]: never; }>;


export type PlanningBoardQuery = { readonly planningProductionOrders: ReadonlyArray<{ readonly __typename: 'ProductionOrder', readonly id: string, readonly number: string, readonly quantity: string, readonly status: string, readonly version: number, readonly article: { readonly __typename: 'Article', readonly id: string, readonly name: string } | null }> };


export const PlanningBoardDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PlanningBoard"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"planningProductionOrders"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"number"}},{"kind":"Field","name":{"kind":"Name","value":"quantity"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"version"}},{"kind":"Field","name":{"kind":"Name","value":"article"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]}}]} as unknown as DocumentNode<PlanningBoardQuery, PlanningBoardQueryVariables>;
