// SPDX-License-Identifier: AGPL-3.0-or-later
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import ts from 'typescript';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { documentFiles, generateDocuments } from '../codegen.ts';

const webDir = resolve(import.meta.dirname, '..');
const committedSchema = readFileSync(resolve(webDir, '../../schema/api.graphql'), 'utf8');

/** The committed schema with one field's line replaced inside the block of `type`. */
function schemaWith(type: string, line: string, replacement: string): string {
  const block = new RegExp(`(type ${type} \\{[^}]*?)  ${line}\\n`);
  expect(committedSchema).toMatch(block);
  return committedSchema.replace(block, (_, head: string) => `${head}${replacement}`);
}

/**
 * The type errors of the web's tsconfig, with each generated file replaced by the one `files`
 * holds: what `pnpm typecheck` would report after `pnpm gen` wrote them. Each error is its file,
 * relative to apps/web, and its message.
 */
function typeErrorsWith(files: readonly { path: string; content: string }[]): string[] {
  const configPath = join(webDir, 'tsconfig.json');
  const { config } = ts.readConfigFile(configPath, ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(config, ts.sys, webDir, undefined, configPath);
  const overlay = new Map(files.map(({ path, content }) => [join(webDir, path), content]));
  const host = ts.createCompilerHost(parsed.options);
  const readFile = host.readFile.bind(host);
  host.readFile = (file) => overlay.get(file) ?? readFile(file);
  const program = ts.createProgram({ rootNames: parsed.fileNames, options: parsed.options, host });
  return ts
    .getPreEmitDiagnostics(program)
    .filter((diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error)
    .map((diagnostic) => {
      const file = diagnostic.file ? relative(webDir, diagnostic.file.fileName) : '(global)';
      return `${file}: ${ts.flattenDiagnosticMessageText(diagnostic.messageText, ' ')}`;
    });
}

describe("the web's typed documents", () => {
  let dir: string;

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'web-codegen-'));
  });

  afterAll(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  /** Generates the web's documents from a schema text. */
  function generateFrom(schema: string) {
    const file = join(dir, 'api.graphql');
    writeFileSync(file, schema);
    return generateDocuments(file);
  }

  it('one <operation>.graphql.gen.ts is generated next to each <operation>.graphql.ts', async () => {
    const files = await generateFrom(committedSchema);

    expect(documentFiles()).toEqual([
      'src/modules/core/article.graphql.ts',
      'src/modules/core/screens/articles/articles.graphql.ts',
      'src/modules/core/screens/edit-article/update-article.graphql.ts',
      'src/modules/core/screens/new-article/create-article.graphql.ts',
      'src/modules/planning/screens/board/board.graphql.ts',
      'src/modules/planning/screens/board/release.graphql.ts',
    ]);
    expect(files.map(({ path }) => path)).toEqual(
      documentFiles().map((path) => path.replace(/\.ts$/, '.gen.ts')),
    );
  });

  it('each generated file says how it is rebuilt', async () => {
    const files = await generateFrom(committedSchema);

    for (const { content } of files) {
      expect(content.split('\n')[0]).toBe(
        '// Generated by pnpm gen from schema/api.graphql and the .graphql.ts file next to it. Do not edit.',
      );
    }
  });

  it('a field the schema no longer has fails the generation, naming the field', async () => {
    const schema = schemaWith('Article', 'name: String!', '');

    await expect(generateFrom(schema)).rejects.toThrow(
      /Cannot query field "name" on type "Article"/,
    );
  });

  it('a field whose type changed fails the typecheck in the screen that reads it until the screen follows', {
    timeout: 120_000,
  }, async () => {
    const unchanged = typeErrorsWith(await generateFrom(committedSchema));
    const changed = typeErrorsWith(
      await generateFrom(schemaWith('Article', 'version: Int!', '  version: String!\n')),
    );

    expect(unchanged).toEqual([]);
    expect(changed.length).toBeGreaterThan(0);
    expect(changed.every((error) => error.startsWith('src/') || error.startsWith('test/'))).toBe(
      true,
    );
    expect(
      changed.some((error) => error.startsWith('src/modules/core/screens/edit-article/')),
    ).toBe(true);
  });
});
